@startuml

title: Классы анализа движка

left to right direction

class Handler{
    execute(Request): Response
}

class CmdComparator{
    compare(string): State {abstract}
}

class Session{
    user: sstring
    set_context(State)
}

class DataAccess{
    connect()
    select_asyncCommands(): List<Synonyms>
    select_currentCommands(): List<Synonyms>
    select_Context(): State
    insert_userContext(user, State)
}

Handler --> CmdComparator
Handler -> DataAccess
CmdComparator -> DataAccess

CmdComparator ^-- LaxComparator
CmdComparator ^-- KeywordSetComparator
CmdComparator ^-- Regression

'Session --> DataAccess
DataAccess <-- Session

@enduml