@startuml

title: Реализация прецедентов работы с файлами

actor "Пользователь" as user
participant Projects
participant ProjectRepository
participant Scenario
participant UserVarRepository
participant UserVar
database DBconnection

group "создание экземпляра проекта"
    user --> Projects : open(File)

    Projects -> ProjectRepository **: File
    alt "не покрывает минимальный шаблон"
        ProjectRepository -> user ++: запрос заполнения минимального шаблона
        return data
        ProjectRepository -> ProjectRepository: save_toFile()
    end

    ProjectRepository -> Scenario **
    ProjectRepository -> DBconnection **
end
/note over user: Пользователь
/note over Projects: Projects
/note over ProjectRepository: ProjectRepository
'/note over Scenario: Scenario
'/note over UserVarRepository: UserVarRepository
'/note over UserVar: UserVar
'/note over DBconnection: DBconnection

Scenario -> user ++ : открыть рабочую область

group "подключение к БД"
    user --> ProjectRepository: connect_toDB(host, user, password)
    ProjectRepository -> Scenario ++: name()
    return db_name
    ProjectRepository -> DBconnection ++: connect(host, user, password, db_name)
end

group "публикация сценария"
    user --> ProjectRepository ++: push_toDB()
    ProjectRepository -> ProjectRepository: save_toFile()
    ProjectRepository -> ProjectRepository:makeSQL()
    ProjectRepository -> DBconnection --: commit()
end

/note over user: Пользователь
/note over Projects: Projects
/note over ProjectRepository: ProjectRepository
/note over Scenario: Scenario
'/note over UserVarRepository: UserVarRepository
'/note over UserVar: UserVar
/note over DBconnection: DBconnection

group "добавление переменной в проект"
    user --> UserVarRepository**: add_var(File, Scenario)
    UserVarRepository -> UserVar **
    UserVarRepository -> Scenario: add_var(UserVar)
    UserVarRepository -> UserVarRepository: save_toFile() 
end

user --> ProjectRepository: save_toFile()

group "редактирование переменной"
    user --> UserVar : update(data)
    UserVar -> UserVarRepository: save_toFile()
end

group "удаление переменной"
    user --> Scenario: remove_var(remove_file)

    alt "remove_file == true"
        Scenario -> UserVarRepository: remove_file()
    end
    
    Scenario -> UserVar!!
    UserVar -> UserVarRepository!!
end

/note over user: Пользователь
/note over Projects: Projects
/note over ProjectRepository: ProjectRepository
/note over Scenario: Scenario
/note over UserVarRepository: UserVarRepository
/note over UserVar: UserVar
/note over DBconnection: DBconnection

group "закрытие проекта"
    user --> Projects --: close(ProjectRepository)
    Projects -> ProjectRepository : save_toFile()
    |||
    Projects -> ProjectRepository !!
    ProjectRepository -> DBconnection : disconnect()
    deactivate DBconnection
    ProjectRepository -> DBconnection !!
    ProjectRepository -> Scenario !!
    Scenario -> UserVar !!
    UserVar -> UserVarRepository !!
end

@enduml